development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://buildurfaye.com/faye"
  secret_token: "89ab2cab280b12579add482355d4259e315dc4d7e7f3c591746a92b1dccb0235"
  signature_expiration: 3600 # one hour
